#!/usr/bin/env python3
"""
Generate Q15 LUTs used by both the firmware (lib/mfcc/src/tables.cpp)
and the Python mirror (scripts/mfcc_tables.py).

Outputs:
  - lib/mfcc/src/tables.cpp  (C++ const arrays)
  - scripts/mfcc_tables.py   (numpy arrays)

Tables generated:
  1. hamming_lut[256]                    int16 Q15
  2. twiddle_cos[128], twiddle_sin[128]  int16 Q15
  3. mel_filter_bank[26]                 packed struct
  4. log2_lut[1024], log2_slopes[1024]   int16 Q15
  5. dct_q15[13][26]                     int16 Q15
"""

import numpy as np
from pathlib import Path

FFT_SIZE = 256
N_MEL = 26
N_DCT = 13
SAMPLE_RATE = 8000
LOG2_LUT_SIZE = 1024


def hamming_lut():
    """h[n] = round((0.54 - 0.46 * cos(2π·n/(N-1))) * 32767), n=0..255"""
    n = np.arange(FFT_SIZE)
    raw = 0.54 - 0.46 * np.cos(2 * np.pi * n / (FFT_SIZE - 1))
    return np.round(raw * 32767).astype(np.int16)


def twiddle_factors():
    """W^k = cos(2πk/N) - j·sin(2πk/N), k=0..127, Q15."""
    k = np.arange(FFT_SIZE // 2)
    cos = np.round(np.cos(2 * np.pi * k / FFT_SIZE) * 32767).astype(np.int16)
    sin = np.round(np.sin(2 * np.pi * k / FFT_SIZE) * 32767).astype(np.int16)
    return cos, sin


def mel_filter_bank():
    """
    26 triangular MEL filters between 0 and 4 kHz.
    Returns list of dicts: {start, peak, end, coefs_q15} per filter.
    """
    def hz_to_mel(f):
        return 2595.0 * np.log10(1.0 + f / 700.0)

    def mel_to_hz(m):
        return 700.0 * (10 ** (m / 2595.0) - 1.0)

    # 28 mel points equally spaced (26 filters need 28 boundary points)
    mel_lo = hz_to_mel(0)
    mel_hi = hz_to_mel(SAMPLE_RATE / 2)
    mel_points = np.linspace(mel_lo, mel_hi, N_MEL + 2)
    hz_points = mel_to_hz(mel_points)
    bin_points = np.floor(hz_points * FFT_SIZE / SAMPLE_RATE).astype(int)

    filters = []
    for m in range(1, N_MEL + 1):
        left, peak, right = bin_points[m - 1], bin_points[m], bin_points[m + 1]
        coefs = []
        for k in range(left, right + 1):
            if k < peak:
                w = (k - left) / max(peak - left, 1)
            elif k == peak:
                w = 1.0
            else:
                w = (right - k) / max(right - peak, 1)
            coefs.append(int(round(w * 32767)))
        filters.append({
            "start": int(left),
            "peak": int(peak),
            "end": int(right + 1),  # exclusive
            "coefs_q15": coefs,
        })
    return filters


def log2_lut():
    """
    log2(x) for x in [1, 2), sampled at 1024 points, Q15.
    Result is in [0, 1) Q15. Slopes for linear interpolation between samples.
    """
    x = 1.0 + np.arange(LOG2_LUT_SIZE) / LOG2_LUT_SIZE  # [1, 1+1/1024, ..., 2-1/1024]
    log2_vals = np.log2(x)  # [0, ..., ~1)
    lut = np.round(log2_vals * 32767).astype(np.int16)

    # Slopes: difference to next sample, scaled. Used for linear interp.
    slopes = np.diff(lut, append=int(round(np.log2(2.0) * 32767)))
    return lut, slopes.astype(np.int16)


def dct_matrix():
    """dct_q15[k][m] = round(cos((m + 0.5) * k * π / N_MEL) * 32767), Q15."""
    mat = np.zeros((N_DCT, N_MEL), dtype=np.int16)
    for k in range(N_DCT):
        for m in range(N_MEL):
            v = np.cos((m + 0.5) * k * np.pi / N_MEL)
            mat[k, m] = int(round(v * 32767))
    return mat


def write_cpp(out_path):
    hamming = hamming_lut()
    tw_cos, tw_sin = twiddle_factors()
    filters = mel_filter_bank()
    log2_v, log2_s = log2_lut()
    dct_m = dct_matrix()

    def fmt_array(arr, per_line=8):
        lines = []
        for i in range(0, len(arr), per_line):
            chunk = ", ".join(f"{int(v):6d}" for v in arr[i:i+per_line])
            lines.append("    " + chunk + ",")
        return "\n".join(lines)

    with open(out_path, "w") as f:
        f.write('// AUTO-GENERATED by scripts/gen_tables.py — DO NOT EDIT BY HAND\n')
        f.write('#include "tables.h"\n\n')

        f.write("const int16_t HAMMING_LUT[256] = {\n")
        f.write(fmt_array(hamming) + "\n};\n\n")

        f.write("const int16_t TWIDDLE_COS[128] = {\n")
        f.write(fmt_array(tw_cos) + "\n};\n\n")

        f.write("const int16_t TWIDDLE_SIN[128] = {\n")
        f.write(fmt_array(tw_sin) + "\n};\n\n")

        f.write("const int16_t LOG2_LUT[1024] = {\n")
        f.write(fmt_array(log2_v) + "\n};\n\n")

        f.write("const int16_t LOG2_SLOPES[1024] = {\n")
        f.write(fmt_array(log2_s) + "\n};\n\n")

        f.write("const int16_t DCT_Q15[13][26] = {\n")
        for k in range(N_DCT):
            row = ", ".join(f"{int(v):6d}" for v in dct_m[k])
            f.write(f"    {{ {row} }},\n")
        f.write("};\n\n")

        # Mel filter bank — variable-length coefs per filter
        max_coefs = max(len(flt["coefs_q15"]) for flt in filters)
        f.write(f"const uint8_t MEL_MAX_COEFS = {max_coefs};\n\n")
        f.write("const MelFilter MEL_FILTERS[26] = {\n")
        for flt in filters:
            coefs = flt["coefs_q15"] + [0] * (max_coefs - len(flt["coefs_q15"]))
            coefs_str = ", ".join(f"{c:6d}" for c in coefs)
            f.write(f"    {{ {flt['start']:3d}, {flt['peak']:3d}, {flt['end']:3d}, {{ {coefs_str} }} }},\n")
        f.write("};\n")


def write_python(out_path):
    hamming = hamming_lut()
    tw_cos, tw_sin = twiddle_factors()
    filters = mel_filter_bank()
    log2_v, log2_s = log2_lut()
    dct_m = dct_matrix()

    with open(out_path, "w") as f:
        f.write('"""AUTO-GENERATED by scripts/gen_tables.py — DO NOT EDIT BY HAND"""\n')
        f.write('import numpy as np\n\n')
        f.write(f'HAMMING_LUT = np.array({hamming.tolist()}, dtype=np.int16)\n\n')
        f.write(f'TWIDDLE_COS = np.array({tw_cos.tolist()}, dtype=np.int16)\n')
        f.write(f'TWIDDLE_SIN = np.array({tw_sin.tolist()}, dtype=np.int16)\n\n')
        f.write(f'LOG2_LUT = np.array({log2_v.tolist()}, dtype=np.int16)\n')
        f.write(f'LOG2_SLOPES = np.array({log2_s.tolist()}, dtype=np.int16)\n\n')
        f.write(f'DCT_Q15 = np.array({dct_m.tolist()}, dtype=np.int16)\n\n')
        f.write('MEL_FILTERS = [\n')
        for flt in filters:
            f.write(f'    dict(start={flt["start"]}, peak={flt["peak"]}, '
                    f'end={flt["end"]}, coefs_q15=np.array({flt["coefs_q15"]}, dtype=np.int16)),\n')
        f.write(']\n')


if __name__ == "__main__":
    root = Path(__file__).parent.parent
    write_cpp(root / "lib" / "mfcc" / "src" / "tables.cpp")
    write_python(root / "scripts" / "mfcc_tables.py")
    print("Generated:")
    print("  lib/mfcc/src/tables.cpp")
    print("  scripts/mfcc_tables.py")
